// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/microhq/proxy-srv/proto/proxy.proto

/*
Package proxy is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/proxy-srv/proto/proxy.proto

It has these top-level messages:
	Pair
	Request
	Response
*/
package proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	api "github.com/micro/go-api"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Proxy service

type ProxyService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type proxyService struct {
	c    client.Client
	name string
}

func NewProxyService(name string, c client.Client) ProxyService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proxy"
	}
	return &proxyService{
		c:    c,
		name: name,
	}
}

func (c *proxyService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Proxy.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Proxy service

type ProxyHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterProxyHandler(s server.Server, hdlr ProxyHandler, opts ...server.HandlerOption) error {
	type proxy interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type Proxy struct {
		proxy
	}
	h := &proxyHandler{hdlr}
	return s.Handle(s.NewHandler(&Proxy{h}, opts...))
}

type proxyHandler struct {
	ProxyHandler
}

func (h *proxyHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ProxyHandler.Call(ctx, in, out)
}
