// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/proxy-srv/proto/proxy.proto

/*
Package proxy is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/proxy-srv/proto/proxy.proto

It has these top-level messages:
	Pair
	Request
	Response
*/
package proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pair struct {
	Key    string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// Request represents a deconstructed http request sent to
type Request struct {
	Method string           `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Path   string           `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Header map[string]*Pair `protobuf:"bytes,3,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Get    map[string]*Pair `protobuf:"bytes,4,rep,name=get" json:"get,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Post   map[string]*Pair `protobuf:"bytes,5,rep,name=post" json:"post,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body   string           `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetGet() map[string]*Pair {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetPost() map[string]*Pair {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// Response
type Response struct {
	StatusCode int32            `protobuf:"varint,1,opt,name=statusCode" json:"statusCode,omitempty"`
	Header     map[string]*Pair `protobuf:"bytes,2,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body       string           `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Pair)(nil), "proxy.Pair")
	proto.RegisterType((*Request)(nil), "proxy.Request")
	proto.RegisterType((*Response)(nil), "proxy.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Proxy service

type ProxyClient interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type proxyClient struct {
	c           client.Client
	serviceName string
}

func NewProxyClient(serviceName string, c client.Client) ProxyClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proxy"
	}
	return &proxyClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *proxyClient) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Proxy.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Proxy service

type ProxyHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterProxyHandler(s server.Server, hdlr ProxyHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Proxy{hdlr}, opts...))
}

type Proxy struct {
	ProxyHandler
}

func (h *Proxy) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ProxyHandler.Call(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/micro/proxy-srv/proto/proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x6f, 0xe2, 0x30,
	0x10, 0xdd, 0xc4, 0x49, 0x16, 0x26, 0xd2, 0xee, 0xca, 0x87, 0xad, 0x95, 0x4a, 0x15, 0xcd, 0x09,
	0x24, 0x1a, 0xaa, 0x70, 0xa9, 0x7a, 0xa5, 0x5f, 0x47, 0xe4, 0x7f, 0x10, 0x88, 0x45, 0x50, 0x01,
	0xa7, 0xb1, 0x83, 0x9a, 0x9f, 0xd4, 0xdf, 0xd0, 0x3f, 0x57, 0x79, 0x62, 0x10, 0x45, 0x9c, 0x50,
	0x6f, 0x6f, 0x66, 0xde, 0xbc, 0xbc, 0xbc, 0x31, 0x0c, 0x17, 0x4b, 0x5d, 0xd4, 0xb3, 0x64, 0x2e,
	0xd7, 0xa3, 0xf5, 0x72, 0x5e, 0xc9, 0x51, 0x59, 0xc9, 0xf7, 0xe6, 0x46, 0x55, 0x5b, 0x83, 0xb4,
	0xad, 0x13, 0xc4, 0xd4, 0xc7, 0x22, 0xbe, 0x05, 0x6f, 0x9a, 0x2d, 0x2b, 0xfa, 0x0f, 0xc8, 0xab,
	0x68, 0x98, 0xd3, 0x73, 0xfa, 0x5d, 0x6e, 0x20, 0xfd, 0x0f, 0xc1, 0x36, 0x5b, 0xd5, 0x42, 0x31,
	0xb7, 0x47, 0xfa, 0x5d, 0x6e, 0xab, 0xf8, 0x83, 0xc0, 0x6f, 0x2e, 0xde, 0x6a, 0xa1, 0xb4, 0xe1,
	0xac, 0x85, 0x2e, 0x64, 0x6e, 0x17, 0x6d, 0x45, 0x29, 0x78, 0x65, 0xa6, 0x0b, 0xe6, 0x62, 0x17,
	0x31, 0x4d, 0x21, 0x28, 0x44, 0x96, 0x8b, 0x8a, 0x91, 0x1e, 0xe9, 0x87, 0x69, 0x94, 0xb4, 0x76,
	0xac, 0x56, 0xf2, 0x82, 0xc3, 0xc7, 0x8d, 0xae, 0x1a, 0x6e, 0x99, 0x74, 0x00, 0x64, 0x21, 0x34,
	0xf3, 0x70, 0xe1, 0xe2, 0x68, 0xe1, 0x59, 0xe8, 0x96, 0x6d, 0x38, 0x74, 0x08, 0x5e, 0x29, 0x95,
	0x66, 0x3e, 0x72, 0xd9, 0x11, 0x77, 0x2a, 0x95, 0x25, 0x23, 0xcb, 0x18, 0x9c, 0xc9, 0xbc, 0x61,
	0x41, 0x6b, 0xd0, 0xe0, 0xe8, 0x09, 0xc2, 0x03, 0x0f, 0x27, 0x12, 0xb9, 0x06, 0x1f, 0x33, 0xc0,
	0xdf, 0x0a, 0xd3, 0xd0, 0x7e, 0xc3, 0xe4, 0xc7, 0xdb, 0xc9, 0xbd, 0x7b, 0xe7, 0x44, 0x13, 0xe8,
	0xec, 0xac, 0x9d, 0x2f, 0xf2, 0x00, 0xdd, 0xbd, 0xe7, 0xb3, 0x55, 0xe2, 0x4f, 0x07, 0x3a, 0x5c,
	0xa8, 0x52, 0x6e, 0x94, 0xa0, 0x57, 0x00, 0x4a, 0x67, 0xba, 0x56, 0x13, 0x99, 0x0b, 0x14, 0xf3,
	0xf9, 0x41, 0x87, 0x8e, 0xf7, 0x07, 0x72, 0x31, 0xc3, 0xcb, 0x7d, 0x86, 0xad, 0xc0, 0xc9, 0x0b,
	0xed, 0x82, 0x24, 0x3f, 0x1f, 0x64, 0x9a, 0x82, 0x3f, 0x35, 0x03, 0x3a, 0x00, 0x6f, 0x92, 0xad,
	0x56, 0xf4, 0xcf, 0xf7, 0xab, 0x46, 0x7f, 0x8f, 0x1c, 0xc6, 0xbf, 0x66, 0x01, 0xbe, 0xee, 0xf1,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x88, 0x03, 0x76, 0xd7, 0x0d, 0x03, 0x00, 0x00,
}
